apiVersion: v2
description: authentik is an open-source Identity Provider focused on flexibility and versatility
name: authentik
home: https://goauthentik.io
sources:
  - https://github.com/goauthentik/authentik
  - https://goauthentik.io/docs/
keywords:
  - proxy
  - oauth
  - authentication
  - saml
  - sso
  - identity
  - single-sign-on
  - ldap
  - idp
  - sp
version: 2.2.1
appVersion: 2021.8.4
icon: https://raw.githubusercontent.com/BeryJu/authentik/master/web/icons/icon.svg
maintainers:
  - name: BeryJu
    email: jens@beryju.org
    url: https://github.com/BeryJu
  - name: dirtycajunrice
    email: nick@cajun.pro
    url: https://github.com/dirtycajunrice
dependencies:
  - name: postgresql
    version: 10.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 14.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 2.4.0
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: App version update to 2021.8.4
    - kind: added
      description: Make avatar mode configurable
    - kind: deprecated
      description: Deprecate authentik.authentik fields
  artifacthub.io/license: GPL-3.0-only
  artifacthub.io/links: |
    - name: Github
      url: https://github.com/goauthentik/authentik
    - name: Docs
      url: https://goauthentik.io/docs/
  artifacthub.io/maintainers: |
    - name: Jens L. BeryJu
      email: jens@beryju.org
      url: https://beryju.org
    - name: Nicholas St. Germain
      email: nick@cajun.pro
      url: https://github.com/dirtycajunrice
  artifacthub.io/images: |
    - name: authentik
      image: ghcr.io/goauthentik/server:2021.8.4
    - name: authentik-outpost-proxy
      image: ghcr.io/goauthentik/proxy:2021.8.4
    - name: authentik-outpost-ldap
      image: ghcr.io/goauthentik/ldap:2021.8.4
